Issue #SB-22862 feat: Collection CSV Hierarchy feature
project-sunbird/knowledge-platform pull request #639
Opened 2021-06-03 09:34 UTC by Jayaprakash8887

Generalization of Collection Editor - Utility for Upload/Download/Update collection hierarchy through csv

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Ran manual test cases
- [X] Ran unit test cases

**Test Configuration**:
* Software versions: Java 11, scala-2.11, play-2.7.2
* Hardware versions:

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-07 10:34 UTC, maheshkumargangula requested changes

2021-06-07 17:35 UTC, Jayaprakash8887 commented on content-api/content-service/app/utils/ApiId.scala
> +	val DOWNLOAD_TOC = "api.collection.toc.download"
code update done as per review comments

2021-06-07 17:35 UTC, Jayaprakash8887 commented on content-api/content-service/conf/routes
> +GET    /v4/collection/toc/download/:collectionId          controllers.v4.CollectionCSVController.getTOCUrl(collectionId:String)
code update done as per review comments

2021-06-11 05:19 UTC, maheshkumargangula requested changes

2021-06-15 05:20 UTC, Jayaprakash8887 commented on content-api/collection-csv-actors/src/main/scala/org.sunbird/collectioncsv/manager/CollectionCSVManager.scala
> +    }
done

2021-06-15 05:36 UTC, maheshkumargangula approved these changes

2021-06-15 07:19 UTC, merged