Issue #KN-231 feat: Added the support for google-cloud.
project-sunbird/knowledge-platform pull request #872
Opened 2022-08-30 05:40 UTC by AmiableAnil

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java 11, scala-2.11, play-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-01 04:49 UTC, vinukumar-vs requested changes

2022-09-01 04:49 UTC, vinukumar-vs commented on content-api/content-actors/src/main/scala/org/sunbird/content/actors/ContentActor.scala
> +		val mimeType: String = request.get("mimeType").asInstanceOf[String]
Why are we looking for mimeType here?

2022-09-01 04:49 UTC, vinukumar-vs commented on content-api/content-actors/src/main/scala/org/sunbird/content/actors/ContentActor.scala
> +			val preSignedURL = ss.getSignedURL(objectKey, Option.apply(expiry.toInt), Option.apply("w"), Option.apply(mimeType))
Why are we sending mimetype information to the library? Liberary should not check this property..

@maheshkumargangula

2022-09-01 04:49 UTC, vinukumar-vs commented on platform-modules/mimetype-manager/src/main/scala/org/sunbird/cloudstore/StorageService.scala
> +      storageType match {
Good to see code improvements

2022-09-01 10:32 UTC, vinukumar-vs approved these changes

2022-09-01 10:33 UTC, vinukumar-vs commented on content-api/content-actors/src/main/scala/org/sunbird/content/actors/ContentActor.scala
> +		val mimeType: String = request.get("mimeType").asInstanceOf[String]
Only for GCP we are sending. For AWS & Azure even though request doesn't have, it's not breaking.

2022-09-01 10:33 UTC, vinukumar-vs approved these changes

2022-09-05 04:45 UTC, AmiableAnil commented
@gandham-santhosh We have added the GCP related changes to this PR and also renamed the few method. For some of the class unit test was not available and I have added the unit test for the recent changes. Currently coverage is 46.7% for this PR. I request you to please merge this PR. We will add the coverage in the upcoming release.

2022-09-05 06:00 UTC, merged